# .github/workflows/main.yaml
name: CI Workflow

on: [push]

jobs:
  rspec-job:
    runs-on: ubuntu-latest
    container:
      image: zulhfreelancer/ruby_nodejs:latest
    steps:
      - name: Start database
        run: service postgresql start
      - name: Check dependency versions
        run: ruby -v && node -v && bundler -v && psql -V
