# .github/workflows/main.yaml
name: CI Workflow

on: [push]

jobs:
  rspec-job:
    runs-on: ubuntu-latest
    container:
      image: zulhfreelancer/ruby_nodejs:latest
    steps:
      - name: Print stuffs
        run: ruby -v
