# .github/workflows/main.yaml
name: CI Workflow

on: [push]

jobs:
  rspec-job:
    runs-on: ubuntu-latest
    container:
      image: zulhfreelancer/ruby_nodejs@b117916b0954
    steps:
      - name: "Print stuffs"
      - uses: actions/checkout@v2
      - run: echo ${{ruby -v}}
