# .github/workflows/main.yaml
name: CI Workflow

on: [push]

jobs:
  rspec-job:
    runs-on: ubuntu-latest
    env:
      # Docs: https://www.postgresql.org/docs/11/libpq-envars.html
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      BUNDLE_CACHE_ALL: true
      BUNDLE_PATH: /vendor/bundle
      BUNDLE_CACHE_PATH: /vendor/bundle
      BUNDLE_BIN: /vendor/bundle
      RAILS_ENV: test
    container:
      image: zulhfreelancer/ruby_nodejs:latest
      volumes:
        - /vendor/bundle
    steps:
      - uses: actions/checkout@v2
      - name: Start database
        run: service postgresql start
      - name: Check dependency versions
        run: ruby -v && node -v && bundler -v && psql -V
      - name: Print working directory and files
        run: pwd && ls -la
      - name: Print environment variables
        run: echo $HOME && echo $GITHUB_WORKSPACE && echo $BUNDLE_BIN
      - name: Wait for database
        run: pg_isready -d "postgresql://postgres:postgres@localhost:5432"
      - uses: actions/cache@v1
        with:
          path: /vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Build & create DB
        run: |
          bundler env
          gem environment
